backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/select-work/index.md'
        label: 'Selected Work'
        name: 'selected-work'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'select-work' }
          - {
              label: Portfolio,
              name: portfolio,
              widget: list,
              fields:
                [
                  { label: 'Title', name: title, widget: string },
                  { label: 'Description', name: 'description', widget: string },
                  { label: 'Image', name: image, widget: image },
                ],
            }
