backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/portfolio/index.md'
        label: 'Portfolio'
        name: 'portfolio'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'product-page',
            }
          - {
              label: Portfolio,
              name: portfolio,
              widget: list,
              fields:
                [
                  { label: 'Title', name: title, widget: string },
                  { label: 'Description', name: 'description', widget: string },
                  { label: 'Image', name: image, widget: image },
                ],
            }
